server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ms-pedidos

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
      connection-timeout: 20000

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect

    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

catalog:
  service:
    url: ${CATALOG_SERVICE_URL:http://ms-catalogo:8082}